/* Ages 7-9: 315 self-contained questions for future gameplay integration. */
const QUESTIONS_7_9 = [
  {
    id: "7-9-1",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐳",
    prompt: "Which animal is a mammal?",
    choices: ["Whale", "Trout", "Butterfly"],
    correct: "Whale",
  },
  {
    id: "7-9-2",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦇",
    prompt: "Which mammal can fly using wings?",
    choices: ["Bat", "Rabbit", "Fox"],
    correct: "Bat",
  },
  {
    id: "7-9-3",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐸",
    prompt: "A frog belongs to which group?",
    choices: ["Amphibians", "Birds", "Mammals"],
    correct: "Amphibians",
  },
  {
    id: "7-9-4",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐍",
    prompt: "A snake belongs to which group?",
    choices: ["Reptiles", "Insects", "Birds"],
    correct: "Reptiles",
  },
  {
    id: "7-9-5",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐜",
    prompt: "How many legs does an insect have?",
    choices: ["6", "8", "4"],
    correct: "6",
  },
  {
    id: "7-9-6",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🕷️",
    prompt: "How many legs does a spider have?",
    choices: ["8", "6", "10"],
    correct: "8",
  },
  {
    id: "7-9-7",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦋",
    prompt: "What does a caterpillar become in a butterfly's life cycle?",
    choices: ["Butterfly", "Tadpole", "Chick"],
    correct: "Butterfly",
  },
  {
    id: "7-9-8",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐸",
    prompt: "What does a tadpole grow into?",
    choices: ["Frog", "Fish", "Turtle"],
    correct: "Frog",
  },
  {
    id: "7-9-9",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐟",
    prompt: "What do most fish use to take oxygen from water?",
    choices: ["Gills", "Feathers", "Horns"],
    correct: "Gills",
  },
  {
    id: "7-9-10",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐻‍❄️",
    prompt: "Which feature helps polar bears stay warm?",
    choices: ["Thick fur and fat", "Thin feathers", "Large fins"],
    correct: "Thick fur and fat",
  },
  {
    id: "7-9-11",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦆",
    prompt: "What helps a duck paddle through water?",
    choices: ["Webbed feet", "Horns", "Claws shaped like wings"],
    correct: "Webbed feet",
  },
  {
    id: "7-9-12",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦉",
    prompt: "An animal active mostly at night is called what?",
    choices: ["Nocturnal", "Aquatic", "Extinct"],
    correct: "Nocturnal",
  },
  {
    id: "7-9-13",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐄",
    prompt: "An animal that eats plants is called what?",
    choices: ["Herbivore", "Carnivore", "Mineral"],
    correct: "Herbivore",
  },
  {
    id: "7-9-14",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦁",
    prompt: "An animal that eats other animals is called what?",
    choices: ["Carnivore", "Herbivore", "Seedling"],
    correct: "Carnivore",
  },
  {
    id: "7-9-15",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐻",
    prompt: "An animal that eats plants and animals is called what?",
    choices: ["Omnivore", "Herbivore", "Carnivore"],
    correct: "Omnivore",
  },
  {
    id: "7-9-16",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🌿 🐛 🐦",
    prompt: "In this food chain, what does the bird eat?",
    choices: ["Caterpillar", "Sunlight", "Soil"],
    correct: "Caterpillar",
  },
  {
    id: "7-9-17",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐝",
    prompt: "How can bees help flowering plants?",
    choices: [
      "Move pollen between flowers",
      "Turn roots into rocks",
      "Remove all sunlight",
    ],
    correct: "Move pollen between flowers",
  },
  {
    id: "7-9-18",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🦎",
    prompt: "How can camouflage help an animal?",
    choices: [
      "Help it blend into its surroundings",
      "Make it louder",
      "Give it extra legs",
    ],
    correct: "Help it blend into its surroundings",
  },
  {
    id: "7-9-19",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐧",
    prompt: "A penguin belongs to which group?",
    choices: ["Birds", "Fish", "Reptiles"],
    correct: "Birds",
  },
  {
    id: "7-9-20",
    ageGroup: "7-9",
    type: "Animal science",
    picture: "🐢",
    prompt: "A sea turtle belongs to which group?",
    choices: ["Reptiles", "Mammals", "Amphibians"],
    correct: "Reptiles",
  },
  {
    id: "7-9-21",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🌍",
    prompt: "What causes day and night on Earth?",
    choices: [
      "Earth spins",
      "The Sun switches off",
      "Clouds cover all of Earth",
    ],
    correct: "Earth spins",
  },
  {
    id: "7-9-22",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "☀️",
    prompt: "The Sun is what kind of object?",
    choices: ["Star", "Planet", "Moon"],
    correct: "Star",
  },
  {
    id: "7-9-23",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🌙",
    prompt: "Why can we see the Moon shining?",
    choices: [
      "It reflects sunlight",
      "It makes sunlight",
      "It is a giant lamp",
    ],
    correct: "It reflects sunlight",
  },
  {
    id: "7-9-24",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🌍",
    prompt: "About how long does Earth take to travel around the Sun?",
    choices: ["One year", "One day", "One week"],
    correct: "One year",
  },
  {
    id: "7-9-25",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🪐",
    prompt: "Which planet is famous for its large rings?",
    choices: ["Saturn", "Earth", "Mars"],
    correct: "Saturn",
  },
  {
    id: "7-9-26",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🔴",
    prompt: "Which planet is called the Red Planet?",
    choices: ["Mars", "Venus", "Neptune"],
    correct: "Mars",
  },
  {
    id: "7-9-27",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🌧️",
    prompt: "Water falling from clouds is called what?",
    choices: ["Precipitation", "Evaporation", "Rotation"],
    correct: "Precipitation",
  },
  {
    id: "7-9-28",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "💧 ☀️",
    prompt: "Liquid water changing into water vapor is called what?",
    choices: ["Evaporation", "Freezing", "Melting"],
    correct: "Evaporation",
  },
  {
    id: "7-9-29",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "☁️",
    prompt: "Water vapor cooling into liquid drops is called what?",
    choices: ["Condensation", "Melting", "Orbiting"],
    correct: "Condensation",
  },
  {
    id: "7-9-30",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🪨",
    prompt: "What is soil often made of?",
    choices: [
      "Rock pieces and decayed living material",
      "Only plastic",
      "Only air",
    ],
    correct: "Rock pieces and decayed living material",
  },
  {
    id: "7-9-31",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🌋",
    prompt: "What is molten rock called after it reaches Earth's surface?",
    choices: ["Lava", "Ice", "Soil"],
    correct: "Lava",
  },
  {
    id: "7-9-32",
    ageGroup: "7-9",
    type: "Earth and space",
    picture: "🧭",
    prompt: "Which direction is opposite north?",
    choices: ["South", "East", "West"],
    correct: "South",
  },
  {
    id: "7-9-33",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🧊",
    prompt: "Ice is which state of matter?",
    choices: ["Solid", "Liquid", "Gas"],
    correct: "Solid",
  },
  {
    id: "7-9-34",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "💧",
    prompt: "Water you pour into a cup is which state of matter?",
    choices: ["Liquid", "Solid", "Gas"],
    correct: "Liquid",
  },
  {
    id: "7-9-35",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🎈",
    prompt: "Air inside a balloon is which state of matter?",
    choices: ["Gas", "Solid", "Liquid"],
    correct: "Gas",
  },
  {
    id: "7-9-36",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🧲",
    prompt: "Which material is attracted strongly to a magnet?",
    choices: ["Iron", "Wood", "Glass"],
    correct: "Iron",
  },
  {
    id: "7-9-37",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🔦",
    prompt: "Which material lets light pass through clearly?",
    choices: ["Clear glass", "Cardboard", "Wood"],
    correct: "Clear glass",
  },
  {
    id: "7-9-38",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🌑",
    prompt: "What makes a shadow?",
    choices: [
      "An object blocks light",
      "An object creates water",
      "Air turns black",
    ],
    correct: "An object blocks light",
  },
  {
    id: "7-9-39",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "⚽",
    prompt: "Which force pulls a dropped ball toward Earth?",
    choices: ["Gravity", "Magnetism", "Sound"],
    correct: "Gravity",
  },
  {
    id: "7-9-40",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🛝",
    prompt: "Which force slows a sliding object as surfaces rub?",
    choices: ["Friction", "Sunlight", "Evaporation"],
    correct: "Friction",
  },
  {
    id: "7-9-41",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🌡️",
    prompt: "Which tool measures temperature?",
    choices: ["Thermometer", "Ruler", "Compass"],
    correct: "Thermometer",
  },
  {
    id: "7-9-42",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "📏",
    prompt: "Which tool measures length?",
    choices: ["Ruler", "Clock", "Thermometer"],
    correct: "Ruler",
  },
  {
    id: "7-9-43",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "🌱",
    prompt: "To test how light affects plants, what should you change?",
    choices: [
      "Only the amount of light",
      "Light, water, and soil together",
      "Only the plant's name",
    ],
    correct: "Only the amount of light",
  },
  {
    id: "7-9-44",
    ageGroup: "7-9",
    type: "Matter and experiments",
    picture: "📝",
    prompt: "Why record results during an experiment?",
    choices: [
      "To compare what happened",
      "To change the results",
      "To avoid observing",
    ],
    correct: "To compare what happened",
  },
  {
    id: "7-9-45",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌿",
    prompt: "Which plant parts usually make food using sunlight?",
    choices: ["Leaves", "Roots", "Seeds"],
    correct: "Leaves",
  },
  {
    id: "7-9-46",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌱",
    prompt: "What do roots absorb from soil?",
    choices: ["Water and minerals", "Sunlight", "Plastic"],
    correct: "Water and minerals",
  },
  {
    id: "7-9-47",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌻",
    prompt: "What is the main job of a flower in a flowering plant?",
    choices: [
      "Help produce seeds",
      "Absorb water from deep soil",
      "Hold soil in place",
    ],
    correct: "Help produce seeds",
  },
  {
    id: "7-9-48",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌱",
    prompt: "What is a seed beginning to grow called?",
    choices: ["Germination", "Condensation", "Migration"],
    correct: "Germination",
  },
  {
    id: "7-9-49",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌵",
    prompt: "What can a cactus store in its thick stem?",
    choices: ["Water", "Sand", "Feathers"],
    correct: "Water",
  },
  {
    id: "7-9-50",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌳",
    prompt: "What supports a plant and carries water between roots and leaves?",
    choices: ["Stem", "Petal", "Pollen"],
    correct: "Stem",
  },
  {
    id: "7-9-51",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🍃",
    prompt: "What gas do plants take in to make food using sunlight?",
    choices: ["Carbon dioxide", "Helium", "Neon"],
    correct: "Carbon dioxide",
  },
  {
    id: "7-9-52",
    ageGroup: "7-9",
    type: "Plant science",
    picture: "🌼",
    prompt: "What is the process of plants making food using light called?",
    choices: ["Photosynthesis", "Hibernation", "Erosion"],
    correct: "Photosynthesis",
  },
  {
    id: "7-9-53",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt:
      "Mia put on boots because puddles covered the path. What was the path like?",
    choices: ["Wet", "Dry", "Frozen solid"],
    correct: "Wet",
  },
  {
    id: "7-9-54",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt:
      "Ben watered a seed each day. A sprout appeared. What happened first?",
    choices: [
      "Ben watered the seed",
      "A sprout appeared",
      "The sprout became a tree",
    ],
    correct: "Ben watered the seed",
  },
  {
    id: "7-9-55",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt: "Sam shivered and zipped up a coat. How did Sam probably feel?",
    choices: ["Cold", "Hot", "Full"],
    correct: "Cold",
  },
  {
    id: "7-9-56",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt:
      "Ava practiced piano every day and learned the song. What helped her learn?",
    choices: ["Practice", "Hiding the piano", "Never playing"],
    correct: "Practice",
  },
  {
    id: "7-9-57",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt: "Leo lent his friend a pencil. Which word describes Leo's action?",
    choices: ["Helpful", "Unkind", "Careless"],
    correct: "Helpful",
  },
  {
    id: "7-9-58",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt:
      "The puppy wagged its tail and ran to greet Jo. How did it probably feel?",
    choices: ["Excited", "Sleepy", "Bored"],
    correct: "Excited",
  },
  {
    id: "7-9-59",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt: "Rain began, so Nia moved her picnic indoors. Why did she move?",
    choices: ["To stay out of the rain", "To see more stars", "To get wet"],
    correct: "To stay out of the rain",
  },
  {
    id: "7-9-60",
    ageGroup: "7-9",
    type: "Reading meaning",
    picture: "📖",
    prompt: "First mix the batter, then bake the cake. What happens second?",
    choices: ["Bake the cake", "Mix the batter", "Buy a plate"],
    correct: "Bake the cake",
  },
  {
    id: "7-9-61",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word is a noun in 'The dog runs'?",
    choices: ["Dog", "Runs", "The"],
    correct: "Dog",
  },
  {
    id: "7-9-62",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word is a verb in 'Birds sing loudly'?",
    choices: ["Sing", "Birds", "Loudly"],
    correct: "Sing",
  },
  {
    id: "7-9-63",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word describes the noun in 'a fluffy cat'?",
    choices: ["Fluffy", "Cat", "A"],
    correct: "Fluffy",
  },
  {
    id: "7-9-64",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word means nearly the same as happy?",
    choices: ["Glad", "Angry", "Tired"],
    correct: "Glad",
  },
  {
    id: "7-9-65",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word means the opposite of brave?",
    choices: ["Fearful", "Bold", "Helpful"],
    correct: "Fearful",
  },
  {
    id: "7-9-66",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "What is the plural of child?",
    choices: ["Children", "Childs", "Childes"],
    correct: "Children",
  },
  {
    id: "7-9-67",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "What is the past tense of go?",
    choices: ["Went", "Goed", "Going"],
    correct: "Went",
  },
  {
    id: "7-9-68",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which mark usually ends a question?",
    choices: ["Question mark", "Comma", "Apostrophe"],
    correct: "Question mark",
  },
  {
    id: "7-9-69",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "What does the prefix un- mean in unhappy?",
    choices: ["Not", "Again", "Before"],
    correct: "Not",
  },
  {
    id: "7-9-70",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "What does the prefix re- mean in reread?",
    choices: ["Again", "Not", "Under"],
    correct: "Again",
  },
  {
    id: "7-9-71",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which pair makes the compound word sunshine?",
    choices: ["Sun and shine", "Sunny and ship", "Son and shell"],
    correct: "Sun and shine",
  },
  {
    id: "7-9-72",
    ageGroup: "7-9",
    type: "Grammar and vocabulary",
    picture: "✏️",
    prompt: "Which word is a contraction of do not?",
    choices: ["Don't", "Does", "Done"],
    correct: "Don't",
  },
  {
    id: "7-9-73",
    ageGroup: "7-9",
    type: "Place value",
    picture: "13",
    prompt: "How many tens are in 13?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "7-9-74",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "5 10 15 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-75",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 1 nickels worth?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-76",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 1 o'clock. What hour will it be two hours later?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "7-9-77",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "1 × 2",
    prompt: "What is 1 times 2?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "7-9-78",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "3 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "7-9-79",
    ageGroup: "7-9",
    type: "Place value",
    picture: "23",
    prompt: "How many tens are in 23?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "7-9-80",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "10 15 20 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-81",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 2 nickels worth?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-82",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 2 o'clock. What hour will it be two hours later?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-83",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "2 × 2",
    prompt: "What is 2 times 2?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-84",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "6 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "7-9-85",
    ageGroup: "7-9",
    type: "Place value",
    picture: "33",
    prompt: "How many tens are in 33?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "7-9-86",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "15 20 25 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["30", "31", "29"],
    correct: "30",
  },
  {
    id: "7-9-87",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 3 nickels worth?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-88",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 3 o'clock. What hour will it be two hours later?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-89",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "3 × 2",
    prompt: "What is 3 times 2?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-90",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "9 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "7-9-91",
    ageGroup: "7-9",
    type: "Place value",
    picture: "43",
    prompt: "How many tens are in 43?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-92",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "20 25 30 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["35", "36", "34"],
    correct: "35",
  },
  {
    id: "7-9-93",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 4 nickels worth?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-94",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 4 o'clock. What hour will it be two hours later?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-95",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "4 × 2",
    prompt: "What is 4 times 2?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-96",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "12 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-97",
    ageGroup: "7-9",
    type: "Place value",
    picture: "53",
    prompt: "How many tens are in 53?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-98",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "25 30 35 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["40", "41", "39"],
    correct: "40",
  },
  {
    id: "7-9-99",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 5 nickels worth?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-100",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 5 o'clock. What hour will it be two hours later?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-101",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "5 × 2",
    prompt: "What is 5 times 2?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-102",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "15 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-103",
    ageGroup: "7-9",
    type: "Place value",
    picture: "63",
    prompt: "How many tens are in 63?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-104",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "30 35 40 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["45", "46", "44"],
    correct: "45",
  },
  {
    id: "7-9-105",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 6 nickels worth?",
    choices: ["30", "31", "29"],
    correct: "30",
  },
  {
    id: "7-9-106",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 6 o'clock. What hour will it be two hours later?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-107",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "6 × 2",
    prompt: "What is 6 times 2?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-108",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "18 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-109",
    ageGroup: "7-9",
    type: "Place value",
    picture: "73",
    prompt: "How many tens are in 73?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-110",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "35 40 45 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["50", "51", "49"],
    correct: "50",
  },
  {
    id: "7-9-111",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 7 nickels worth?",
    choices: ["35", "36", "34"],
    correct: "35",
  },
  {
    id: "7-9-112",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 7 o'clock. What hour will it be two hours later?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-113",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "7 × 2",
    prompt: "What is 7 times 2?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-114",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "21 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-115",
    ageGroup: "7-9",
    type: "Place value",
    picture: "83",
    prompt: "How many tens are in 83?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-116",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "40 45 50 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["55", "56", "54"],
    correct: "55",
  },
  {
    id: "7-9-117",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 8 nickels worth?",
    choices: ["40", "41", "39"],
    correct: "40",
  },
  {
    id: "7-9-118",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 8 o'clock. What hour will it be two hours later?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-119",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "8 × 2",
    prompt: "What is 8 times 2?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-120",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "24 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-121",
    ageGroup: "7-9",
    type: "Place value",
    picture: "93",
    prompt: "How many tens are in 93?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-122",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "45 50 55 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["60", "61", "59"],
    correct: "60",
  },
  {
    id: "7-9-123",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 9 nickels worth?",
    choices: ["45", "46", "44"],
    correct: "45",
  },
  {
    id: "7-9-124",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 9 o'clock. What hour will it be two hours later?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-125",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "9 × 2",
    prompt: "What is 9 times 2?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-126",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "27 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-127",
    ageGroup: "7-9",
    type: "Place value",
    picture: "103",
    prompt: "How many tens are in 103?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-128",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "50 55 60 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["65", "66", "64"],
    correct: "65",
  },
  {
    id: "7-9-129",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 10 nickels worth?",
    choices: ["50", "51", "49"],
    correct: "50",
  },
  {
    id: "7-9-130",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 10 o'clock. What hour will it be two hours later?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-131",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "10 × 2",
    prompt: "What is 10 times 2?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-132",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "30 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-133",
    ageGroup: "7-9",
    type: "Place value",
    picture: "113",
    prompt: "How many tens are in 113?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-134",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "55 60 65 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["70", "71", "69"],
    correct: "70",
  },
  {
    id: "7-9-135",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 11 nickels worth?",
    choices: ["55", "56", "54"],
    correct: "55",
  },
  {
    id: "7-9-136",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 11 o'clock. What hour will it be two hours later?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "7-9-137",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "11 × 2",
    prompt: "What is 11 times 2?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-138",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "33 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-139",
    ageGroup: "7-9",
    type: "Place value",
    picture: "123",
    prompt: "How many tens are in 123?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-140",
    ageGroup: "7-9",
    type: "Skip counting",
    picture: "60 65 70 ❓",
    prompt: "Count by fives. What comes next?",
    choices: ["75", "76", "74"],
    correct: "75",
  },
  {
    id: "7-9-141",
    ageGroup: "7-9",
    type: "Money",
    picture: "🪙",
    prompt: "How many cents are 12 nickels worth?",
    choices: ["60", "61", "59"],
    correct: "60",
  },
  {
    id: "7-9-142",
    ageGroup: "7-9",
    type: "Time",
    picture: "🕒",
    prompt: "It is 12 o'clock. What hour will it be two hours later?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "7-9-143",
    ageGroup: "7-9",
    type: "Multiplying",
    picture: "12 × 2",
    prompt: "What is 12 times 2?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-144",
    ageGroup: "7-9",
    type: "Dividing",
    picture: "🍪",
    prompt:
      "36 cookies are shared equally by 3 children. How many does each child get?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-145",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "🍕",
    prompt: "A pizza is cut into 4 equal pieces. One piece is what fraction?",
    choices: ["One fourth", "One half", "One third"],
    correct: "One fourth",
  },
  {
    id: "7-9-146",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "🍎",
    prompt:
      "An apple is split into 2 equal pieces. One piece is what fraction?",
    choices: ["One half", "One fourth", "One whole"],
    correct: "One half",
  },
  {
    id: "7-9-147",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "🍰",
    prompt: "You eat 2 of 4 equal cake pieces. What fraction did you eat?",
    choices: ["One half", "One fourth", "One whole"],
    correct: "One half",
  },
  {
    id: "7-9-148",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "📐",
    prompt: "How many sides does a hexagon have?",
    choices: ["6", "5", "8"],
    correct: "6",
  },
  {
    id: "7-9-149",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "📐",
    prompt: "How many sides does a pentagon have?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-150",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "📐",
    prompt: "How many corners does a rectangle have?",
    choices: ["4", "3", "6"],
    correct: "4",
  },
  {
    id: "7-9-151",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "🎲",
    prompt: "How many square faces does a cube have?",
    choices: ["6", "4", "8"],
    correct: "6",
  },
  {
    id: "7-9-152",
    ageGroup: "7-9",
    type: "Fractions and geometry",
    picture: "⚽",
    prompt: "Which solid shape is a ball most like?",
    choices: ["Sphere", "Cube", "Cone"],
    correct: "Sphere",
  },
  {
    id: "7-9-153",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 2",
    prompt: "What is 12 plus 2?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-154",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 2",
    prompt: "What is 12 minus 2?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-155",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 3",
    prompt: "What is 12 plus 3?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-156",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 3",
    prompt: "What is 12 minus 3?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-157",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 4",
    prompt: "What is 12 plus 4?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-158",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 4",
    prompt: "What is 12 minus 4?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-159",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 5",
    prompt: "What is 12 plus 5?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-160",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 5",
    prompt: "What is 12 minus 5?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-161",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 6",
    prompt: "What is 12 plus 6?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-162",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 6",
    prompt: "What is 12 minus 6?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-163",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 7",
    prompt: "What is 12 plus 7?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-164",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 7",
    prompt: "What is 12 minus 7?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-165",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 8",
    prompt: "What is 12 plus 8?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-166",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 8",
    prompt: "What is 12 minus 8?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-167",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "12 + 9",
    prompt: "What is 12 plus 9?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-168",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "12 − 9",
    prompt: "What is 12 minus 9?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "7-9-169",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 2",
    prompt: "What is 13 plus 2?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-170",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 2",
    prompt: "What is 13 minus 2?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-171",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 3",
    prompt: "What is 13 plus 3?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-172",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 3",
    prompt: "What is 13 minus 3?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-173",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 4",
    prompt: "What is 13 plus 4?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-174",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 4",
    prompt: "What is 13 minus 4?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-175",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 5",
    prompt: "What is 13 plus 5?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-176",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 5",
    prompt: "What is 13 minus 5?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-177",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 6",
    prompt: "What is 13 plus 6?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-178",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 6",
    prompt: "What is 13 minus 6?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-179",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 7",
    prompt: "What is 13 plus 7?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-180",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 7",
    prompt: "What is 13 minus 7?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-181",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 8",
    prompt: "What is 13 plus 8?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-182",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 8",
    prompt: "What is 13 minus 8?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-183",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "13 + 9",
    prompt: "What is 13 plus 9?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-184",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "13 − 9",
    prompt: "What is 13 minus 9?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "7-9-185",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 2",
    prompt: "What is 14 plus 2?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-186",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 2",
    prompt: "What is 14 minus 2?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-187",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 3",
    prompt: "What is 14 plus 3?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-188",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 3",
    prompt: "What is 14 minus 3?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-189",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 4",
    prompt: "What is 14 plus 4?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-190",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 4",
    prompt: "What is 14 minus 4?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-191",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 5",
    prompt: "What is 14 plus 5?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-192",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 5",
    prompt: "What is 14 minus 5?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-193",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 6",
    prompt: "What is 14 plus 6?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-194",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 6",
    prompt: "What is 14 minus 6?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-195",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 7",
    prompt: "What is 14 plus 7?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-196",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 7",
    prompt: "What is 14 minus 7?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-197",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 8",
    prompt: "What is 14 plus 8?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-198",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 8",
    prompt: "What is 14 minus 8?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-199",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "14 + 9",
    prompt: "What is 14 plus 9?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-200",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "14 − 9",
    prompt: "What is 14 minus 9?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "7-9-201",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 2",
    prompt: "What is 15 plus 2?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-202",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 2",
    prompt: "What is 15 minus 2?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-203",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 3",
    prompt: "What is 15 plus 3?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-204",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 3",
    prompt: "What is 15 minus 3?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-205",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 4",
    prompt: "What is 15 plus 4?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-206",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 4",
    prompt: "What is 15 minus 4?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-207",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 5",
    prompt: "What is 15 plus 5?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-208",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 5",
    prompt: "What is 15 minus 5?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-209",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 6",
    prompt: "What is 15 plus 6?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-210",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 6",
    prompt: "What is 15 minus 6?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-211",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 7",
    prompt: "What is 15 plus 7?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-212",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 7",
    prompt: "What is 15 minus 7?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-213",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 8",
    prompt: "What is 15 plus 8?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-214",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 8",
    prompt: "What is 15 minus 8?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-215",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "15 + 9",
    prompt: "What is 15 plus 9?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-216",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "15 − 9",
    prompt: "What is 15 minus 9?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "7-9-217",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 2",
    prompt: "What is 16 plus 2?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-218",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 2",
    prompt: "What is 16 minus 2?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-219",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 3",
    prompt: "What is 16 plus 3?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-220",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 3",
    prompt: "What is 16 minus 3?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-221",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 4",
    prompt: "What is 16 plus 4?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-222",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 4",
    prompt: "What is 16 minus 4?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-223",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 5",
    prompt: "What is 16 plus 5?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-224",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 5",
    prompt: "What is 16 minus 5?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-225",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 6",
    prompt: "What is 16 plus 6?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-226",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 6",
    prompt: "What is 16 minus 6?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-227",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 7",
    prompt: "What is 16 plus 7?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-228",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 7",
    prompt: "What is 16 minus 7?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-229",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 8",
    prompt: "What is 16 plus 8?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-230",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 8",
    prompt: "What is 16 minus 8?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-231",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "16 + 9",
    prompt: "What is 16 plus 9?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-232",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "16 − 9",
    prompt: "What is 16 minus 9?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "7-9-233",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 2",
    prompt: "What is 17 plus 2?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-234",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 2",
    prompt: "What is 17 minus 2?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-235",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 3",
    prompt: "What is 17 plus 3?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-236",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 3",
    prompt: "What is 17 minus 3?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-237",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 4",
    prompt: "What is 17 plus 4?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-238",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 4",
    prompt: "What is 17 minus 4?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-239",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 5",
    prompt: "What is 17 plus 5?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-240",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 5",
    prompt: "What is 17 minus 5?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-241",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 6",
    prompt: "What is 17 plus 6?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-242",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 6",
    prompt: "What is 17 minus 6?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-243",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 7",
    prompt: "What is 17 plus 7?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-244",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 7",
    prompt: "What is 17 minus 7?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-245",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 8",
    prompt: "What is 17 plus 8?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-246",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 8",
    prompt: "What is 17 minus 8?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-247",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "17 + 9",
    prompt: "What is 17 plus 9?",
    choices: ["26", "27", "25"],
    correct: "26",
  },
  {
    id: "7-9-248",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "17 − 9",
    prompt: "What is 17 minus 9?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "7-9-249",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 2",
    prompt: "What is 18 plus 2?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-250",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 2",
    prompt: "What is 18 minus 2?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-251",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 3",
    prompt: "What is 18 plus 3?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-252",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 3",
    prompt: "What is 18 minus 3?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-253",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 4",
    prompt: "What is 18 plus 4?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-254",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 4",
    prompt: "What is 18 minus 4?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-255",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 5",
    prompt: "What is 18 plus 5?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-256",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 5",
    prompt: "What is 18 minus 5?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-257",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 6",
    prompt: "What is 18 plus 6?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-258",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 6",
    prompt: "What is 18 minus 6?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-259",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 7",
    prompt: "What is 18 plus 7?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-260",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 7",
    prompt: "What is 18 minus 7?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-261",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 8",
    prompt: "What is 18 plus 8?",
    choices: ["26", "27", "25"],
    correct: "26",
  },
  {
    id: "7-9-262",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 8",
    prompt: "What is 18 minus 8?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-263",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "18 + 9",
    prompt: "What is 18 plus 9?",
    choices: ["27", "28", "26"],
    correct: "27",
  },
  {
    id: "7-9-264",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "18 − 9",
    prompt: "What is 18 minus 9?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "7-9-265",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 2",
    prompt: "What is 19 plus 2?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "7-9-266",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 2",
    prompt: "What is 19 minus 2?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-267",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 3",
    prompt: "What is 19 plus 3?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-268",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 3",
    prompt: "What is 19 minus 3?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-269",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 4",
    prompt: "What is 19 plus 4?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-270",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 4",
    prompt: "What is 19 minus 4?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-271",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 5",
    prompt: "What is 19 plus 5?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-272",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 5",
    prompt: "What is 19 minus 5?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-273",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 6",
    prompt: "What is 19 plus 6?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-274",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 6",
    prompt: "What is 19 minus 6?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-275",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 7",
    prompt: "What is 19 plus 7?",
    choices: ["26", "27", "25"],
    correct: "26",
  },
  {
    id: "7-9-276",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 7",
    prompt: "What is 19 minus 7?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-277",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 8",
    prompt: "What is 19 plus 8?",
    choices: ["27", "28", "26"],
    correct: "27",
  },
  {
    id: "7-9-278",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 8",
    prompt: "What is 19 minus 8?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-279",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "19 + 9",
    prompt: "What is 19 plus 9?",
    choices: ["28", "29", "27"],
    correct: "28",
  },
  {
    id: "7-9-280",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "19 − 9",
    prompt: "What is 19 minus 9?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "7-9-281",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 2",
    prompt: "What is 20 plus 2?",
    choices: ["22", "23", "21"],
    correct: "22",
  },
  {
    id: "7-9-282",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 2",
    prompt: "What is 20 minus 2?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-283",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 3",
    prompt: "What is 20 plus 3?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-284",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 3",
    prompt: "What is 20 minus 3?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-285",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 4",
    prompt: "What is 20 plus 4?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-286",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 4",
    prompt: "What is 20 minus 4?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-287",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 5",
    prompt: "What is 20 plus 5?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-288",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 5",
    prompt: "What is 20 minus 5?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-289",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 6",
    prompt: "What is 20 plus 6?",
    choices: ["26", "27", "25"],
    correct: "26",
  },
  {
    id: "7-9-290",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 6",
    prompt: "What is 20 minus 6?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-291",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 7",
    prompt: "What is 20 plus 7?",
    choices: ["27", "28", "26"],
    correct: "27",
  },
  {
    id: "7-9-292",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 7",
    prompt: "What is 20 minus 7?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-293",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 8",
    prompt: "What is 20 plus 8?",
    choices: ["28", "29", "27"],
    correct: "28",
  },
  {
    id: "7-9-294",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 8",
    prompt: "What is 20 minus 8?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-295",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "20 + 9",
    prompt: "What is 20 plus 9?",
    choices: ["29", "30", "28"],
    correct: "29",
  },
  {
    id: "7-9-296",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "20 − 9",
    prompt: "What is 20 minus 9?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "7-9-297",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 2",
    prompt: "What is 21 plus 2?",
    choices: ["23", "24", "22"],
    correct: "23",
  },
  {
    id: "7-9-298",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 2",
    prompt: "What is 21 minus 2?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "7-9-299",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 3",
    prompt: "What is 21 plus 3?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-300",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 3",
    prompt: "What is 21 minus 3?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "7-9-301",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 4",
    prompt: "What is 21 plus 4?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
  {
    id: "7-9-302",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 4",
    prompt: "What is 21 minus 4?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "7-9-303",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 5",
    prompt: "What is 21 plus 5?",
    choices: ["26", "27", "25"],
    correct: "26",
  },
  {
    id: "7-9-304",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 5",
    prompt: "What is 21 minus 5?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "7-9-305",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 6",
    prompt: "What is 21 plus 6?",
    choices: ["27", "28", "26"],
    correct: "27",
  },
  {
    id: "7-9-306",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 6",
    prompt: "What is 21 minus 6?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "7-9-307",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 7",
    prompt: "What is 21 plus 7?",
    choices: ["28", "29", "27"],
    correct: "28",
  },
  {
    id: "7-9-308",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 7",
    prompt: "What is 21 minus 7?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "7-9-309",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 8",
    prompt: "What is 21 plus 8?",
    choices: ["29", "30", "28"],
    correct: "29",
  },
  {
    id: "7-9-310",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 8",
    prompt: "What is 21 minus 8?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "7-9-311",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "21 + 9",
    prompt: "What is 21 plus 9?",
    choices: ["30", "31", "29"],
    correct: "30",
  },
  {
    id: "7-9-312",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "21 − 9",
    prompt: "What is 21 minus 9?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "7-9-313",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "22 + 2",
    prompt: "What is 22 plus 2?",
    choices: ["24", "25", "23"],
    correct: "24",
  },
  {
    id: "7-9-314",
    ageGroup: "7-9",
    type: "Two-digit subtracting",
    picture: "22 − 2",
    prompt: "What is 22 minus 2?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "7-9-315",
    ageGroup: "7-9",
    type: "Two-digit adding",
    picture: "22 + 3",
    prompt: "What is 22 plus 3?",
    choices: ["25", "26", "24"],
    correct: "25",
  },
];
