/* Ages 5-6: 315 self-contained questions for future gameplay integration. */
const QUESTIONS_5_6 = [
  {
    id: "5-6-1",
    type: "Animal words",
    picture: "🐱",
    prompt: "Which word matches the picture?",
    choices: ["Cat", "Bat", "Mat"],
    correct: "Cat",
    ageGroup: "5-6",
  },
  {
    id: "5-6-2",
    type: "Animal words",
    picture: "🐶",
    prompt: "Which word matches the picture?",
    choices: ["Dog", "Log", "Fog"],
    correct: "Dog",
    ageGroup: "5-6",
  },
  {
    id: "5-6-3",
    type: "Animal words",
    picture: "🐷",
    prompt: "Which word matches the picture?",
    choices: ["Pig", "Dig", "Big"],
    correct: "Pig",
    ageGroup: "5-6",
  },
  {
    id: "5-6-4",
    type: "Animal words",
    picture: "🐔",
    prompt: "Which word matches the picture?",
    choices: ["Hen", "Pen", "Ten"],
    correct: "Hen",
    ageGroup: "5-6",
  },
  {
    id: "5-6-5",
    type: "Animal words",
    picture: "🦊",
    prompt: "Which word matches the picture?",
    choices: ["Fox", "Box", "Pot"],
    correct: "Fox",
    ageGroup: "5-6",
  },
  {
    id: "5-6-6",
    type: "Animal words",
    picture: "🐮",
    prompt: "Which word matches the picture?",
    choices: ["Cow", "Bow", "Now"],
    correct: "Cow",
    ageGroup: "5-6",
  },
  {
    id: "5-6-7",
    type: "Animal words",
    picture: "🐝",
    prompt: "Which word matches the picture?",
    choices: ["Bee", "See", "Tree"],
    correct: "Bee",
    ageGroup: "5-6",
  },
  {
    id: "5-6-8",
    type: "Animal words",
    picture: "🐟",
    prompt: "Which word matches the picture?",
    choices: ["Fish", "Dish", "Ship"],
    correct: "Fish",
    ageGroup: "5-6",
  },
  {
    id: "5-6-9",
    type: "Animal words",
    picture: "🦆",
    prompt: "Which word matches the picture?",
    choices: ["Duck", "Truck", "Sock"],
    correct: "Duck",
    ageGroup: "5-6",
  },
  {
    id: "5-6-10",
    type: "Animal words",
    picture: "🐸",
    prompt: "Which word matches the picture?",
    choices: ["Frog", "Dog", "Log"],
    correct: "Frog",
    ageGroup: "5-6",
  },
  {
    id: "5-6-11",
    type: "Animal words",
    picture: "🦁",
    prompt: "Which word matches the picture?",
    choices: ["Lion", "Tiger", "Bear"],
    correct: "Lion",
    ageGroup: "5-6",
  },
  {
    id: "5-6-12",
    type: "Animal words",
    picture: "🐻",
    prompt: "Which word matches the picture?",
    choices: ["Bear", "Pear", "Deer"],
    correct: "Bear",
    ageGroup: "5-6",
  },
  {
    id: "5-6-13",
    type: "Animal words",
    picture: "🐑",
    prompt: "Which word matches the picture?",
    choices: ["Sheep", "Sleep", "Ship"],
    correct: "Sheep",
    ageGroup: "5-6",
  },
  {
    id: "5-6-14",
    type: "Animal words",
    picture: "🐐",
    prompt: "Which word matches the picture?",
    choices: ["Goat", "Boat", "Coat"],
    correct: "Goat",
    ageGroup: "5-6",
  },
  {
    id: "5-6-15",
    type: "Animal words",
    picture: "🐴",
    prompt: "Which word matches the picture?",
    choices: ["Horse", "House", "Mouse"],
    correct: "Horse",
    ageGroup: "5-6",
  },
  {
    id: "5-6-16",
    type: "Animal words",
    picture: "🐭",
    prompt: "Which word matches the picture?",
    choices: ["Mouse", "House", "Moose"],
    correct: "Mouse",
    ageGroup: "5-6",
  },
  {
    id: "5-6-17",
    type: "Animal words",
    picture: "🐰",
    prompt: "Which word matches the picture?",
    choices: ["Rabbit", "Carrot", "Parrot"],
    correct: "Rabbit",
    ageGroup: "5-6",
  },
  {
    id: "5-6-18",
    type: "Animal words",
    picture: "🐢",
    prompt: "Which word matches the picture?",
    choices: ["Turtle", "Tiger", "Turkey"],
    correct: "Turtle",
    ageGroup: "5-6",
  },
  {
    id: "5-6-19",
    type: "Animal words",
    picture: "🐘",
    prompt: "Which word matches the picture?",
    choices: ["Elephant", "Lion", "Monkey"],
    correct: "Elephant",
    ageGroup: "5-6",
  },
  {
    id: "5-6-20",
    type: "Animal words",
    picture: "🐒",
    prompt: "Which word matches the picture?",
    choices: ["Monkey", "Donkey", "Rabbit"],
    correct: "Monkey",
    ageGroup: "5-6",
  },
  {
    id: "5-6-21",
    type: "Animal words",
    picture: "🦓",
    prompt: "Which word matches the picture?",
    choices: ["Zebra", "Horse", "Giraffe"],
    correct: "Zebra",
    ageGroup: "5-6",
  },
  {
    id: "5-6-22",
    type: "Animal words",
    picture: "🦉",
    prompt: "Which word matches the picture?",
    choices: ["Owl", "Cow", "Crow"],
    correct: "Owl",
    ageGroup: "5-6",
  },
  {
    id: "5-6-23",
    type: "Animal words",
    picture: "🐌",
    prompt: "Which word matches the picture?",
    choices: ["Snail", "Whale", "Snake"],
    correct: "Snail",
    ageGroup: "5-6",
  },
  {
    id: "5-6-24",
    type: "Animal words",
    picture: "🦀",
    prompt: "Which word matches the picture?",
    choices: ["Crab", "Cat", "Crow"],
    correct: "Crab",
    ageGroup: "5-6",
  },
  {
    id: "5-6-25",
    type: "Animal words",
    picture: "🐳",
    prompt: "Which word matches the picture?",
    choices: ["Whale", "Shark", "Seal"],
    correct: "Whale",
    ageGroup: "5-6",
  },
  {
    id: "5-6-26",
    type: "Letter discovery",
    picture: "A",
    prompt: "Which little letter matches?",
    choices: ["a", "f", "l"],
    correct: "a",
    ageGroup: "5-6",
  },
  {
    id: "5-6-27",
    type: "Letter discovery",
    picture: "B",
    prompt: "Which little letter matches?",
    choices: ["b", "g", "m"],
    correct: "b",
    ageGroup: "5-6",
  },
  {
    id: "5-6-28",
    type: "Letter discovery",
    picture: "C",
    prompt: "Which little letter matches?",
    choices: ["c", "h", "n"],
    correct: "c",
    ageGroup: "5-6",
  },
  {
    id: "5-6-29",
    type: "Letter discovery",
    picture: "D",
    prompt: "Which little letter matches?",
    choices: ["d", "i", "o"],
    correct: "d",
    ageGroup: "5-6",
  },
  {
    id: "5-6-30",
    type: "Letter discovery",
    picture: "E",
    prompt: "Which little letter matches?",
    choices: ["e", "j", "p"],
    correct: "e",
    ageGroup: "5-6",
  },
  {
    id: "5-6-31",
    type: "Letter discovery",
    picture: "F",
    prompt: "Which little letter matches?",
    choices: ["f", "k", "q"],
    correct: "f",
    ageGroup: "5-6",
  },
  {
    id: "5-6-32",
    type: "Letter discovery",
    picture: "G",
    prompt: "Which little letter matches?",
    choices: ["g", "l", "r"],
    correct: "g",
    ageGroup: "5-6",
  },
  {
    id: "5-6-33",
    type: "Letter discovery",
    picture: "H",
    prompt: "Which little letter matches?",
    choices: ["h", "m", "s"],
    correct: "h",
    ageGroup: "5-6",
  },
  {
    id: "5-6-34",
    type: "Letter discovery",
    picture: "I",
    prompt: "Which little letter matches?",
    choices: ["i", "n", "t"],
    correct: "i",
    ageGroup: "5-6",
  },
  {
    id: "5-6-35",
    type: "Letter discovery",
    picture: "J",
    prompt: "Which little letter matches?",
    choices: ["j", "o", "u"],
    correct: "j",
    ageGroup: "5-6",
  },
  {
    id: "5-6-36",
    type: "Letter discovery",
    picture: "K",
    prompt: "Which little letter matches?",
    choices: ["k", "p", "v"],
    correct: "k",
    ageGroup: "5-6",
  },
  {
    id: "5-6-37",
    type: "Letter discovery",
    picture: "L",
    prompt: "Which little letter matches?",
    choices: ["l", "q", "w"],
    correct: "l",
    ageGroup: "5-6",
  },
  {
    id: "5-6-38",
    type: "Letter discovery",
    picture: "M",
    prompt: "Which little letter matches?",
    choices: ["m", "r", "x"],
    correct: "m",
    ageGroup: "5-6",
  },
  {
    id: "5-6-39",
    type: "Letter discovery",
    picture: "N",
    prompt: "Which little letter matches?",
    choices: ["n", "s", "y"],
    correct: "n",
    ageGroup: "5-6",
  },
  {
    id: "5-6-40",
    type: "Letter discovery",
    picture: "O",
    prompt: "Which little letter matches?",
    choices: ["o", "t", "z"],
    correct: "o",
    ageGroup: "5-6",
  },
  {
    id: "5-6-41",
    type: "Letter discovery",
    picture: "P",
    prompt: "Which little letter matches?",
    choices: ["p", "u", "a"],
    correct: "p",
    ageGroup: "5-6",
  },
  {
    id: "5-6-42",
    type: "Letter discovery",
    picture: "Q",
    prompt: "Which little letter matches?",
    choices: ["q", "v", "b"],
    correct: "q",
    ageGroup: "5-6",
  },
  {
    id: "5-6-43",
    type: "Letter discovery",
    picture: "R",
    prompt: "Which little letter matches?",
    choices: ["r", "w", "c"],
    correct: "r",
    ageGroup: "5-6",
  },
  {
    id: "5-6-44",
    type: "Letter discovery",
    picture: "S",
    prompt: "Which little letter matches?",
    choices: ["s", "x", "d"],
    correct: "s",
    ageGroup: "5-6",
  },
  {
    id: "5-6-45",
    type: "Letter discovery",
    picture: "T",
    prompt: "Which little letter matches?",
    choices: ["t", "y", "e"],
    correct: "t",
    ageGroup: "5-6",
  },
  {
    id: "5-6-46",
    type: "Letter discovery",
    picture: "U",
    prompt: "Which little letter matches?",
    choices: ["u", "z", "f"],
    correct: "u",
    ageGroup: "5-6",
  },
  {
    id: "5-6-47",
    type: "Letter discovery",
    picture: "V",
    prompt: "Which little letter matches?",
    choices: ["v", "a", "g"],
    correct: "v",
    ageGroup: "5-6",
  },
  {
    id: "5-6-48",
    type: "Letter discovery",
    picture: "W",
    prompt: "Which little letter matches?",
    choices: ["w", "b", "h"],
    correct: "w",
    ageGroup: "5-6",
  },
  {
    id: "5-6-49",
    type: "Letter discovery",
    picture: "X",
    prompt: "Which little letter matches?",
    choices: ["x", "c", "i"],
    correct: "x",
    ageGroup: "5-6",
  },
  {
    id: "5-6-50",
    type: "Letter discovery",
    picture: "Y",
    prompt: "Which little letter matches?",
    choices: ["y", "d", "j"],
    correct: "y",
    ageGroup: "5-6",
  },
  {
    id: "5-6-51",
    type: "Letter discovery",
    picture: "Z",
    prompt: "Which little letter matches?",
    choices: ["z", "e", "k"],
    correct: "z",
    ageGroup: "5-6",
  },
  {
    id: "5-6-52",
    type: "First sounds",
    picture: "🍎",
    prompt: "What letter starts apple?",
    choices: ["A", "E", "J"],
    correct: "A",
    ageGroup: "5-6",
  },
  {
    id: "5-6-53",
    type: "First sounds",
    picture: "⚽",
    prompt: "What letter starts ball?",
    choices: ["B", "F", "K"],
    correct: "B",
    ageGroup: "5-6",
  },
  {
    id: "5-6-54",
    type: "First sounds",
    picture: "🐱",
    prompt: "What letter starts cat?",
    choices: ["C", "G", "L"],
    correct: "C",
    ageGroup: "5-6",
  },
  {
    id: "5-6-55",
    type: "First sounds",
    picture: "🐶",
    prompt: "What letter starts dog?",
    choices: ["D", "H", "M"],
    correct: "D",
    ageGroup: "5-6",
  },
  {
    id: "5-6-56",
    type: "First sounds",
    picture: "🥚",
    prompt: "What letter starts egg?",
    choices: ["E", "I", "N"],
    correct: "E",
    ageGroup: "5-6",
  },
  {
    id: "5-6-57",
    type: "First sounds",
    picture: "🐟",
    prompt: "What letter starts fish?",
    choices: ["F", "J", "O"],
    correct: "F",
    ageGroup: "5-6",
  },
  {
    id: "5-6-58",
    type: "First sounds",
    picture: "🐐",
    prompt: "What letter starts goat?",
    choices: ["G", "K", "P"],
    correct: "G",
    ageGroup: "5-6",
  },
  {
    id: "5-6-59",
    type: "First sounds",
    picture: "🎩",
    prompt: "What letter starts hat?",
    choices: ["H", "L", "Q"],
    correct: "H",
    ageGroup: "5-6",
  },
  {
    id: "5-6-60",
    type: "First sounds",
    picture: "🧊",
    prompt: "What letter starts ice?",
    choices: ["I", "M", "R"],
    correct: "I",
    ageGroup: "5-6",
  },
  {
    id: "5-6-61",
    type: "First sounds",
    picture: "🫙",
    prompt: "What letter starts jar?",
    choices: ["J", "N", "S"],
    correct: "J",
    ageGroup: "5-6",
  },
  {
    id: "5-6-62",
    type: "First sounds",
    picture: "🪁",
    prompt: "What letter starts kite?",
    choices: ["K", "O", "T"],
    correct: "K",
    ageGroup: "5-6",
  },
  {
    id: "5-6-63",
    type: "First sounds",
    picture: "🍋",
    prompt: "What letter starts lemon?",
    choices: ["L", "P", "U"],
    correct: "L",
    ageGroup: "5-6",
  },
  {
    id: "5-6-64",
    type: "First sounds",
    picture: "🌙",
    prompt: "What letter starts moon?",
    choices: ["M", "Q", "V"],
    correct: "M",
    ageGroup: "5-6",
  },
  {
    id: "5-6-65",
    type: "First sounds",
    picture: "🪺",
    prompt: "What letter starts nest?",
    choices: ["N", "R", "W"],
    correct: "N",
    ageGroup: "5-6",
  },
  {
    id: "5-6-66",
    type: "First sounds",
    picture: "🐙",
    prompt: "What letter starts octopus?",
    choices: ["O", "S", "X"],
    correct: "O",
    ageGroup: "5-6",
  },
  {
    id: "5-6-67",
    type: "First sounds",
    picture: "🐷",
    prompt: "What letter starts pig?",
    choices: ["P", "T", "Y"],
    correct: "P",
    ageGroup: "5-6",
  },
  {
    id: "5-6-68",
    type: "First sounds",
    picture: "👑",
    prompt: "What letter starts queen?",
    choices: ["Q", "U", "Z"],
    correct: "Q",
    ageGroup: "5-6",
  },
  {
    id: "5-6-69",
    type: "First sounds",
    picture: "🌈",
    prompt: "What letter starts rainbow?",
    choices: ["R", "V", "A"],
    correct: "R",
    ageGroup: "5-6",
  },
  {
    id: "5-6-70",
    type: "First sounds",
    picture: "☀️",
    prompt: "What letter starts sun?",
    choices: ["S", "W", "B"],
    correct: "S",
    ageGroup: "5-6",
  },
  {
    id: "5-6-71",
    type: "First sounds",
    picture: "🌳",
    prompt: "What letter starts tree?",
    choices: ["T", "X", "C"],
    correct: "T",
    ageGroup: "5-6",
  },
  {
    id: "5-6-72",
    type: "First sounds",
    picture: "☂️",
    prompt: "What letter starts umbrella?",
    choices: ["U", "Y", "D"],
    correct: "U",
    ageGroup: "5-6",
  },
  {
    id: "5-6-73",
    type: "First sounds",
    picture: "🎻",
    prompt: "What letter starts violin?",
    choices: ["V", "Z", "E"],
    correct: "V",
    ageGroup: "5-6",
  },
  {
    id: "5-6-74",
    type: "First sounds",
    picture: "🍉",
    prompt: "What letter starts watermelon?",
    choices: ["W", "A", "F"],
    correct: "W",
    ageGroup: "5-6",
  },
  {
    id: "5-6-75",
    type: "First sounds",
    picture: "🧶",
    prompt: "What letter starts yarn?",
    choices: ["Y", "C", "H"],
    correct: "Y",
    ageGroup: "5-6",
  },
  {
    id: "5-6-76",
    type: "First sounds",
    picture: "🦓",
    prompt: "What letter starts zebra?",
    choices: ["Z", "D", "I"],
    correct: "Z",
    ageGroup: "5-6",
  },
  {
    id: "5-6-77",
    type: "Counting",
    picture: "⭐",
    prompt: "How many stars can you count?",
    choices: ["1", "2", "3"],
    correct: "1",
    ageGroup: "5-6",
  },
  {
    id: "5-6-78",
    type: "Number discovery",
    picture: "1",
    prompt: "Which number is this?",
    choices: ["one", "two", "four"],
    correct: "one",
    ageGroup: "5-6",
  },
  {
    id: "5-6-79",
    type: "Counting",
    picture: "⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["2", "3", "1"],
    correct: "2",
    ageGroup: "5-6",
  },
  {
    id: "5-6-80",
    type: "Number discovery",
    picture: "2",
    prompt: "Which number is this?",
    choices: ["two", "three", "five"],
    correct: "two",
    ageGroup: "5-6",
  },
  {
    id: "5-6-81",
    type: "Counting",
    picture: "⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["3", "4", "2"],
    correct: "3",
    ageGroup: "5-6",
  },
  {
    id: "5-6-82",
    type: "Number discovery",
    picture: "3",
    prompt: "Which number is this?",
    choices: ["three", "four", "six"],
    correct: "three",
    ageGroup: "5-6",
  },
  {
    id: "5-6-83",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["4", "5", "3"],
    correct: "4",
    ageGroup: "5-6",
  },
  {
    id: "5-6-84",
    type: "Number discovery",
    picture: "4",
    prompt: "Which number is this?",
    choices: ["four", "five", "seven"],
    correct: "four",
    ageGroup: "5-6",
  },
  {
    id: "5-6-85",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["5", "6", "4"],
    correct: "5",
    ageGroup: "5-6",
  },
  {
    id: "5-6-86",
    type: "Number discovery",
    picture: "5",
    prompt: "Which number is this?",
    choices: ["five", "six", "eight"],
    correct: "five",
    ageGroup: "5-6",
  },
  {
    id: "5-6-87",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["6", "7", "5"],
    correct: "6",
    ageGroup: "5-6",
  },
  {
    id: "5-6-88",
    type: "Number discovery",
    picture: "6",
    prompt: "Which number is this?",
    choices: ["six", "seven", "nine"],
    correct: "six",
    ageGroup: "5-6",
  },
  {
    id: "5-6-89",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["7", "8", "6"],
    correct: "7",
    ageGroup: "5-6",
  },
  {
    id: "5-6-90",
    type: "Number discovery",
    picture: "7",
    prompt: "Which number is this?",
    choices: ["seven", "eight", "ten"],
    correct: "seven",
    ageGroup: "5-6",
  },
  {
    id: "5-6-91",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["8", "9", "7"],
    correct: "8",
    ageGroup: "5-6",
  },
  {
    id: "5-6-92",
    type: "Number discovery",
    picture: "8",
    prompt: "Which number is this?",
    choices: ["zero", "eight", "nine"],
    correct: "eight",
    ageGroup: "5-6",
  },
  {
    id: "5-6-93",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["9", "10", "8"],
    correct: "9",
    ageGroup: "5-6",
  },
  {
    id: "5-6-94",
    type: "Number discovery",
    picture: "9",
    prompt: "Which number is this?",
    choices: ["one", "nine", "ten"],
    correct: "nine",
    ageGroup: "5-6",
  },
  {
    id: "5-6-95",
    type: "Counting",
    picture: "⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐",
    prompt: "How many stars can you count?",
    choices: ["10", "8", "9"],
    correct: "10",
    ageGroup: "5-6",
  },
  {
    id: "5-6-96",
    type: "Number discovery",
    picture: "10",
    prompt: "Which number is this?",
    choices: ["zero", "two", "ten"],
    correct: "ten",
    ageGroup: "5-6",
  },
  {
    id: "5-6-97",
    type: "Colors",
    picture: "🔴",
    prompt: "What color do you see?",
    choices: ["Red", "Blue", "Green"],
    correct: "Red",
    ageGroup: "5-6",
  },
  {
    id: "5-6-98",
    type: "Colors",
    picture: "🔵",
    prompt: "What color do you see?",
    choices: ["Blue", "Yellow", "Red"],
    correct: "Blue",
    ageGroup: "5-6",
  },
  {
    id: "5-6-99",
    type: "Colors",
    picture: "🟢",
    prompt: "What color do you see?",
    choices: ["Green", "Purple", "Blue"],
    correct: "Green",
    ageGroup: "5-6",
  },
  {
    id: "5-6-100",
    type: "Colors",
    picture: "🟡",
    prompt: "What color do you see?",
    choices: ["Yellow", "Red", "Green"],
    correct: "Yellow",
    ageGroup: "5-6",
  },
  {
    id: "5-6-101",
    type: "Colors",
    picture: "🟣",
    prompt: "What color do you see?",
    choices: ["Purple", "Orange", "Blue"],
    correct: "Purple",
    ageGroup: "5-6",
  },
  {
    id: "5-6-102",
    type: "Colors",
    picture: "🟠",
    prompt: "What color do you see?",
    choices: ["Orange", "Green", "Purple"],
    correct: "Orange",
    ageGroup: "5-6",
  },
  {
    id: "5-6-103",
    type: "Colors",
    picture: "⬛",
    prompt: "What color do you see?",
    choices: ["Black", "White", "Red"],
    correct: "Black",
    ageGroup: "5-6",
  },
  {
    id: "5-6-104",
    type: "Colors",
    picture: "⬜",
    prompt: "What color do you see?",
    choices: ["White", "Black", "Blue"],
    correct: "White",
    ageGroup: "5-6",
  },
  {
    id: "5-6-105",
    type: "Shapes",
    picture: "●",
    prompt: "What shape is this?",
    choices: ["Circle", "Square", "Triangle"],
    correct: "Circle",
    ageGroup: "5-6",
  },
  {
    id: "5-6-106",
    type: "Shapes",
    picture: "■",
    prompt: "What shape is this?",
    choices: ["Square", "Circle", "Triangle"],
    correct: "Square",
    ageGroup: "5-6",
  },
  {
    id: "5-6-107",
    type: "Shapes",
    picture: "▲",
    prompt: "What shape is this?",
    choices: ["Triangle", "Square", "Circle"],
    correct: "Triangle",
    ageGroup: "5-6",
  },
  {
    id: "5-6-108",
    type: "Shapes",
    picture: "★",
    prompt: "What shape is this?",
    choices: ["Star", "Circle", "Square"],
    correct: "Star",
    ageGroup: "5-6",
  },
  {
    id: "5-6-109",
    type: "Patterns",
    picture: "🔴 🔵 🔴 🔵 ❓",
    prompt: "What comes next?",
    choices: ["🔴", "🔵", "🟢"],
    correct: "🔴",
    ageGroup: "5-6",
  },
  {
    id: "5-6-110",
    type: "Patterns",
    picture: "⭐ 🌙 ⭐ 🌙 ❓",
    prompt: "What comes next?",
    choices: ["⭐", "🌙", "☀️"],
    correct: "⭐",
    ageGroup: "5-6",
  },
  {
    id: "5-6-111",
    type: "Patterns",
    picture: "🐱 🐶 🐶 🐱 🐶 ❓",
    prompt: "What comes next?",
    choices: ["🐶", "🐱", "🐭"],
    correct: "🐶",
    ageGroup: "5-6",
  },
  {
    id: "5-6-112",
    type: "Patterns",
    picture: "1 2 3 ❓",
    prompt: "Which number comes next?",
    choices: ["4", "5", "2"],
    correct: "4",
    ageGroup: "5-6",
  },
  {
    id: "5-6-113",
    type: "Patterns",
    picture: "2 4 6 ❓",
    prompt: "Count by twos. What comes next?",
    choices: ["8", "7", "9"],
    correct: "8",
    ageGroup: "5-6",
  },
  {
    id: "5-6-114",
    type: "Patterns",
    picture: "🟡 🟡 🟢 🟡 🟡 ❓",
    prompt: "What comes next?",
    choices: ["🟢", "🟡", "🔵"],
    correct: "🟢",
    ageGroup: "5-6",
  },
  {
    id: "5-6-115",
    type: "Adding",
    picture: "🍎 + 🍎",
    prompt: "One apple plus one apple makes how many?",
    choices: ["2", "1", "3"],
    correct: "2",
    ageGroup: "5-6",
  },
  {
    id: "5-6-116",
    type: "Adding",
    picture: "⭐⭐ + ⭐",
    prompt: "Two stars plus one star makes how many?",
    choices: ["3", "2", "4"],
    correct: "3",
    ageGroup: "5-6",
  },
  {
    id: "5-6-117",
    type: "Adding",
    picture: "🐟🐟 + 🐟🐟",
    prompt: "Two fish plus two fish makes how many?",
    choices: ["4", "3", "5"],
    correct: "4",
    ageGroup: "5-6",
  },
  {
    id: "5-6-118",
    type: "Adding",
    picture: "3 + 2",
    prompt: "What is three plus two?",
    choices: ["5", "4", "6"],
    correct: "5",
    ageGroup: "5-6",
  },
  {
    id: "5-6-119",
    type: "Adding",
    picture: "4 + 1",
    prompt: "What is four plus one?",
    choices: ["5", "3", "6"],
    correct: "5",
    ageGroup: "5-6",
  },
  {
    id: "5-6-120",
    type: "Adding",
    picture: "5 + 2",
    prompt: "What is five plus two?",
    choices: ["7", "6", "8"],
    correct: "7",
    ageGroup: "5-6",
  },
  {
    id: "5-6-121",
    type: "Taking away",
    picture: "🍪🍪🍪",
    prompt: "You eat one of these three cookies. How many are left?",
    choices: ["2", "3", "1"],
    correct: "2",
    ageGroup: "5-6",
  },
  {
    id: "5-6-122",
    type: "Taking away",
    picture: "🎈🎈",
    prompt: "One of these two balloons flies away. How many are left?",
    choices: ["1", "2", "0"],
    correct: "1",
    ageGroup: "5-6",
  },
  {
    id: "5-6-123",
    type: "Taking away",
    picture: "5 − 1",
    prompt: "What is five take away one?",
    choices: ["4", "3", "5"],
    correct: "4",
    ageGroup: "5-6",
  },
  {
    id: "5-6-124",
    type: "Taking away",
    picture: "4 − 2",
    prompt: "What is four take away two?",
    choices: ["2", "1", "3"],
    correct: "2",
    ageGroup: "5-6",
  },
  {
    id: "5-6-125",
    type: "Taking away",
    picture: "3 − 3",
    prompt: "What is three take away three?",
    choices: ["0", "1", "3"],
    correct: "0",
    ageGroup: "5-6",
  },
  {
    id: "5-6-126",
    type: "Taking away",
    picture: "6 − 1",
    prompt: "What is six take away one?",
    choices: ["5", "4", "6"],
    correct: "5",
    ageGroup: "5-6",
  },
  {
    id: "5-6-127",
    type: "Opposites and comparing",
    picture: "🐘 🐭",
    prompt: "Which animal is usually bigger?",
    choices: ["Elephant", "Mouse", "Both the same"],
    correct: "Elephant",
    ageGroup: "5-6",
  },
  {
    id: "5-6-128",
    type: "Opposites and comparing",
    picture: "☀️",
    prompt: "What is the opposite of hot?",
    choices: ["Cold", "Warm", "Big"],
    correct: "Cold",
    ageGroup: "5-6",
  },
  {
    id: "5-6-129",
    type: "Opposites and comparing",
    picture: "⬆️",
    prompt: "What is the opposite of up?",
    choices: ["Down", "Over", "Up"],
    correct: "Down",
    ageGroup: "5-6",
  },
  {
    id: "5-6-130",
    type: "Opposites and comparing",
    picture: "🐢 🐆",
    prompt: "Which animal usually moves more slowly?",
    choices: ["Turtle", "Cheetah", "Both the same"],
    correct: "Turtle",
    ageGroup: "5-6",
  },
  {
    id: "5-6-131",
    type: "Opposites and comparing",
    picture: "🌞 🌙",
    prompt: "What is the opposite of day?",
    choices: ["Night", "Morning", "Lunch"],
    correct: "Night",
    ageGroup: "5-6",
  },
  {
    id: "5-6-132",
    type: "Opposites and comparing",
    picture: "🐘 🪶",
    prompt: "Which is heavier: an elephant or a feather?",
    choices: ["Elephant", "Feather", "Both the same"],
    correct: "Elephant",
    ageGroup: "5-6",
  },
  {
    id: "5-6-133",
    type: "Rhyming",
    picture: "🐱",
    prompt: "Which word rhymes with cat?",
    choices: ["Hat", "Dog", "Sun"],
    correct: "Hat",
    ageGroup: "5-6",
  },
  {
    id: "5-6-134",
    type: "Rhyming",
    picture: "🐶",
    prompt: "Which word rhymes with dog?",
    choices: ["Log", "Cat", "Bed"],
    correct: "Log",
    ageGroup: "5-6",
  },
  {
    id: "5-6-135",
    type: "Rhyming",
    picture: "☀️",
    prompt: "Which word rhymes with sun?",
    choices: ["Run", "Sit", "Top"],
    correct: "Run",
    ageGroup: "5-6",
  },
  {
    id: "5-6-136",
    type: "Rhyming",
    picture: "🐝",
    prompt: "Which word rhymes with bee?",
    choices: ["Tree", "Ball", "Hat"],
    correct: "Tree",
    ageGroup: "5-6",
  },
  {
    id: "5-6-137",
    type: "Rhyming",
    picture: "🐷",
    prompt: "Which word rhymes with pig?",
    choices: ["Big", "Small", "Red"],
    correct: "Big",
    ageGroup: "5-6",
  },
  {
    id: "5-6-138",
    type: "Rhyming",
    picture: "🛏️",
    prompt: "Which word rhymes with bed?",
    choices: ["Red", "Blue", "Green"],
    correct: "Red",
    ageGroup: "5-6",
  },
  {
    id: "5-6-139",
    type: "Sorting",
    picture: "🍎 🍌 🚗",
    prompt: "Which one is not a fruit?",
    choices: ["Car", "Apple", "Banana"],
    correct: "Car",
    ageGroup: "5-6",
  },
  {
    id: "5-6-140",
    type: "Sorting",
    picture: "🐶 🐱 👟",
    prompt: "Which one is not an animal?",
    choices: ["Shoe", "Dog", "Cat"],
    correct: "Shoe",
    ageGroup: "5-6",
  },
  {
    id: "5-6-141",
    type: "Sorting",
    picture: "🧦 👕 🥕",
    prompt: "Which one is not clothing?",
    choices: ["Carrot", "Sock", "Shirt"],
    correct: "Carrot",
    ageGroup: "5-6",
  },
  {
    id: "5-6-142",
    type: "Sorting",
    picture: "🚗 🚌 🐟",
    prompt: "Which one is not a road vehicle?",
    choices: ["Fish", "Car", "Bus"],
    correct: "Fish",
    ageGroup: "5-6",
  },
  {
    id: "5-6-143",
    type: "Sorting",
    picture: "🥁 🎸 🍎",
    prompt: "Which one is not a musical instrument?",
    choices: ["Apple", "Drum", "Guitar"],
    correct: "Apple",
    ageGroup: "5-6",
  },
  {
    id: "5-6-144",
    type: "Sorting",
    picture: "🔴 🔵 ■",
    prompt: "Which one has corners?",
    choices: ["Square", "Red circle", "Blue circle"],
    correct: "Square",
    ageGroup: "5-6",
  },
  {
    id: "5-6-145",
    type: "Our world",
    picture: "🌧️",
    prompt: "What helps keep you dry in the rain?",
    choices: ["Umbrella", "Sunglasses", "Sandals"],
    correct: "Umbrella",
    ageGroup: "5-6",
  },
  {
    id: "5-6-146",
    type: "Our world",
    picture: "❄️",
    prompt: "What keeps your hands warm in snow?",
    choices: ["Mittens", "Socks", "Hat"],
    correct: "Mittens",
    ageGroup: "5-6",
  },
  {
    id: "5-6-147",
    type: "Our world",
    picture: "🌱",
    prompt: "What does a plant need to grow?",
    choices: ["Water", "Candy", "Shoes"],
    correct: "Water",
    ageGroup: "5-6",
  },
  {
    id: "5-6-148",
    type: "Our world",
    picture: "🐦",
    prompt: "What does a bird use to fly?",
    choices: ["Wings", "Fins", "Paws"],
    correct: "Wings",
    ageGroup: "5-6",
  },
  {
    id: "5-6-149",
    type: "Our world",
    picture: "🐟",
    prompt: "Where does a fish live?",
    choices: ["Water", "A tree", "A bed"],
    correct: "Water",
    ageGroup: "5-6",
  },
  {
    id: "5-6-150",
    type: "Our world",
    picture: "👂",
    prompt: "What do you use to hear music?",
    choices: ["Ears", "Eyes", "Nose"],
    correct: "Ears",
    ageGroup: "5-6",
  },
  {
    id: "5-6-151",
    type: "Everyday life",
    picture: "🧼 🙌",
    prompt: "What should you do before eating?",
    choices: ["Wash hands", "Paint hands", "Put on mittens"],
    correct: "Wash hands",
    ageGroup: "5-6",
  },
  {
    id: "5-6-152",
    type: "Everyday life",
    picture: "🪥",
    prompt: "What do you use to brush your teeth?",
    choices: ["Toothbrush", "Hairbrush", "Spoon"],
    correct: "Toothbrush",
    ageGroup: "5-6",
  },
  {
    id: "5-6-153",
    type: "Everyday life",
    picture: "🤝",
    prompt: "Your friend shares a toy. What can you say?",
    choices: ["Thank you", "Go away", "Give me more"],
    correct: "Thank you",
    ageGroup: "5-6",
  },
  {
    id: "5-6-154",
    type: "Everyday life",
    picture: "😢",
    prompt: "Your friend feels sad. What is a kind thing to do?",
    choices: ["Ask if they need help", "Laugh at them", "Hide their toy"],
    correct: "Ask if they need help",
    ageGroup: "5-6",
  },
  {
    id: "5-6-155",
    type: "Everyday life",
    picture: "📚",
    prompt: "What do you do with a storybook?",
    choices: ["Read it", "Eat it", "Wear it"],
    correct: "Read it",
    ageGroup: "5-6",
  },
  {
    id: "5-6-156",
    type: "Everyday life",
    picture: "🌙 🛏️",
    prompt: "You feel sleepy at bedtime. What do you do?",
    choices: ["Go to bed", "Start a race", "Pack lunch"],
    correct: "Go to bed",
    ageGroup: "5-6",
  },
  {
    id: "5-6-157",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 1",
    prompt: "What is 1 plus 1?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-158",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 2",
    prompt: "What is 1 plus 2?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-159",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 3",
    prompt: "What is 1 plus 3?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-160",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 4",
    prompt: "What is 1 plus 4?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-161",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 5",
    prompt: "What is 1 plus 5?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-162",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 6",
    prompt: "What is 1 plus 6?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-163",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 7",
    prompt: "What is 1 plus 7?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-164",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 8",
    prompt: "What is 1 plus 8?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-165",
    ageGroup: "5-6",
    type: "Adding",
    picture: "1 + 9",
    prompt: "What is 1 plus 9?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-166",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 1",
    prompt: "What is 2 plus 1?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-167",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 2",
    prompt: "What is 2 plus 2?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-168",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 3",
    prompt: "What is 2 plus 3?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-169",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 4",
    prompt: "What is 2 plus 4?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-170",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 5",
    prompt: "What is 2 plus 5?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-171",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 6",
    prompt: "What is 2 plus 6?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-172",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 7",
    prompt: "What is 2 plus 7?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-173",
    ageGroup: "5-6",
    type: "Adding",
    picture: "2 + 8",
    prompt: "What is 2 plus 8?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-174",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 1",
    prompt: "What is 3 plus 1?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-175",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 2",
    prompt: "What is 3 plus 2?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-176",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 3",
    prompt: "What is 3 plus 3?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-177",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 4",
    prompt: "What is 3 plus 4?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-178",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 5",
    prompt: "What is 3 plus 5?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-179",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 6",
    prompt: "What is 3 plus 6?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-180",
    ageGroup: "5-6",
    type: "Adding",
    picture: "3 + 7",
    prompt: "What is 3 plus 7?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-181",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 1",
    prompt: "What is 4 plus 1?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-182",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 2",
    prompt: "What is 4 plus 2?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-183",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 3",
    prompt: "What is 4 plus 3?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-184",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 4",
    prompt: "What is 4 plus 4?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-185",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 5",
    prompt: "What is 4 plus 5?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-186",
    ageGroup: "5-6",
    type: "Adding",
    picture: "4 + 6",
    prompt: "What is 4 plus 6?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-187",
    ageGroup: "5-6",
    type: "Adding",
    picture: "5 + 1",
    prompt: "What is 5 plus 1?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-188",
    ageGroup: "5-6",
    type: "Adding",
    picture: "5 + 2",
    prompt: "What is 5 plus 2?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-189",
    ageGroup: "5-6",
    type: "Adding",
    picture: "5 + 3",
    prompt: "What is 5 plus 3?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-190",
    ageGroup: "5-6",
    type: "Adding",
    picture: "5 + 4",
    prompt: "What is 5 plus 4?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-191",
    ageGroup: "5-6",
    type: "Adding",
    picture: "5 + 5",
    prompt: "What is 5 plus 5?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-192",
    ageGroup: "5-6",
    type: "Adding",
    picture: "6 + 1",
    prompt: "What is 6 plus 1?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-193",
    ageGroup: "5-6",
    type: "Adding",
    picture: "6 + 2",
    prompt: "What is 6 plus 2?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-194",
    ageGroup: "5-6",
    type: "Adding",
    picture: "6 + 3",
    prompt: "What is 6 plus 3?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-195",
    ageGroup: "5-6",
    type: "Adding",
    picture: "6 + 4",
    prompt: "What is 6 plus 4?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-196",
    ageGroup: "5-6",
    type: "Adding",
    picture: "7 + 1",
    prompt: "What is 7 plus 1?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-197",
    ageGroup: "5-6",
    type: "Adding",
    picture: "7 + 2",
    prompt: "What is 7 plus 2?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-198",
    ageGroup: "5-6",
    type: "Adding",
    picture: "7 + 3",
    prompt: "What is 7 plus 3?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-199",
    ageGroup: "5-6",
    type: "Adding",
    picture: "8 + 1",
    prompt: "What is 8 plus 1?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-200",
    ageGroup: "5-6",
    type: "Adding",
    picture: "8 + 2",
    prompt: "What is 8 plus 2?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-201",
    ageGroup: "5-6",
    type: "Adding",
    picture: "9 + 1",
    prompt: "What is 9 plus 1?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-202",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "2 − 1",
    prompt: "What is 2 take away 1?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-203",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "2 − 2",
    prompt: "What is 2 take away 2?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-204",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "3 − 1",
    prompt: "What is 3 take away 1?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-205",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "3 − 2",
    prompt: "What is 3 take away 2?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-206",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "3 − 3",
    prompt: "What is 3 take away 3?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-207",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "4 − 1",
    prompt: "What is 4 take away 1?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-208",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "4 − 2",
    prompt: "What is 4 take away 2?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-209",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "4 − 3",
    prompt: "What is 4 take away 3?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-210",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "4 − 4",
    prompt: "What is 4 take away 4?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-211",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "5 − 1",
    prompt: "What is 5 take away 1?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-212",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "5 − 2",
    prompt: "What is 5 take away 2?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-213",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "5 − 3",
    prompt: "What is 5 take away 3?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-214",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "5 − 4",
    prompt: "What is 5 take away 4?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-215",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "5 − 5",
    prompt: "What is 5 take away 5?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-216",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 1",
    prompt: "What is 6 take away 1?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-217",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 2",
    prompt: "What is 6 take away 2?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-218",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 3",
    prompt: "What is 6 take away 3?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-219",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 4",
    prompt: "What is 6 take away 4?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-220",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 5",
    prompt: "What is 6 take away 5?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-221",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "6 − 6",
    prompt: "What is 6 take away 6?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-222",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 1",
    prompt: "What is 7 take away 1?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-223",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 2",
    prompt: "What is 7 take away 2?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-224",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 3",
    prompt: "What is 7 take away 3?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-225",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 4",
    prompt: "What is 7 take away 4?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-226",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 5",
    prompt: "What is 7 take away 5?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-227",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 6",
    prompt: "What is 7 take away 6?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-228",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "7 − 7",
    prompt: "What is 7 take away 7?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-229",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 1",
    prompt: "What is 8 take away 1?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-230",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 2",
    prompt: "What is 8 take away 2?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-231",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 3",
    prompt: "What is 8 take away 3?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-232",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 4",
    prompt: "What is 8 take away 4?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-233",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 5",
    prompt: "What is 8 take away 5?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-234",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 6",
    prompt: "What is 8 take away 6?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-235",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 7",
    prompt: "What is 8 take away 7?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-236",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "8 − 8",
    prompt: "What is 8 take away 8?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-237",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 1",
    prompt: "What is 9 take away 1?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-238",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 2",
    prompt: "What is 9 take away 2?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-239",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 3",
    prompt: "What is 9 take away 3?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-240",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 4",
    prompt: "What is 9 take away 4?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-241",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 5",
    prompt: "What is 9 take away 5?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-242",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 6",
    prompt: "What is 9 take away 6?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-243",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 7",
    prompt: "What is 9 take away 7?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-244",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 8",
    prompt: "What is 9 take away 8?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-245",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "9 − 9",
    prompt: "What is 9 take away 9?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-246",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 1",
    prompt: "What is 10 take away 1?",
    choices: ["9", "10", "8"],
    correct: "9",
  },
  {
    id: "5-6-247",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 2",
    prompt: "What is 10 take away 2?",
    choices: ["8", "9", "7"],
    correct: "8",
  },
  {
    id: "5-6-248",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 3",
    prompt: "What is 10 take away 3?",
    choices: ["7", "8", "6"],
    correct: "7",
  },
  {
    id: "5-6-249",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 4",
    prompt: "What is 10 take away 4?",
    choices: ["6", "7", "5"],
    correct: "6",
  },
  {
    id: "5-6-250",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 5",
    prompt: "What is 10 take away 5?",
    choices: ["5", "6", "4"],
    correct: "5",
  },
  {
    id: "5-6-251",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 6",
    prompt: "What is 10 take away 6?",
    choices: ["4", "5", "3"],
    correct: "4",
  },
  {
    id: "5-6-252",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 7",
    prompt: "What is 10 take away 7?",
    choices: ["3", "4", "2"],
    correct: "3",
  },
  {
    id: "5-6-253",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 8",
    prompt: "What is 10 take away 8?",
    choices: ["2", "3", "1"],
    correct: "2",
  },
  {
    id: "5-6-254",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 9",
    prompt: "What is 10 take away 9?",
    choices: ["1", "2", "0"],
    correct: "1",
  },
  {
    id: "5-6-255",
    ageGroup: "5-6",
    type: "Taking away",
    picture: "10 − 10",
    prompt: "What is 10 take away 10?",
    choices: ["0", "1", "2"],
    correct: "0",
  },
  {
    id: "5-6-256",
    ageGroup: "5-6",
    type: "Number order",
    picture: "11 → ❓",
    prompt: "Which number comes just after 11?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "5-6-257",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 11",
    prompt: "Which number comes just before 11?",
    choices: ["10", "11", "9"],
    correct: "10",
  },
  {
    id: "5-6-258",
    ageGroup: "5-6",
    type: "Number order",
    picture: "12 → ❓",
    prompt: "Which number comes just after 12?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "5-6-259",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 12",
    prompt: "Which number comes just before 12?",
    choices: ["11", "12", "10"],
    correct: "11",
  },
  {
    id: "5-6-260",
    ageGroup: "5-6",
    type: "Number order",
    picture: "13 → ❓",
    prompt: "Which number comes just after 13?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "5-6-261",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 13",
    prompt: "Which number comes just before 13?",
    choices: ["12", "13", "11"],
    correct: "12",
  },
  {
    id: "5-6-262",
    ageGroup: "5-6",
    type: "Number order",
    picture: "14 → ❓",
    prompt: "Which number comes just after 14?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "5-6-263",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 14",
    prompt: "Which number comes just before 14?",
    choices: ["13", "14", "12"],
    correct: "13",
  },
  {
    id: "5-6-264",
    ageGroup: "5-6",
    type: "Number order",
    picture: "15 → ❓",
    prompt: "Which number comes just after 15?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "5-6-265",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 15",
    prompt: "Which number comes just before 15?",
    choices: ["14", "15", "13"],
    correct: "14",
  },
  {
    id: "5-6-266",
    ageGroup: "5-6",
    type: "Number order",
    picture: "16 → ❓",
    prompt: "Which number comes just after 16?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "5-6-267",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 16",
    prompt: "Which number comes just before 16?",
    choices: ["15", "16", "14"],
    correct: "15",
  },
  {
    id: "5-6-268",
    ageGroup: "5-6",
    type: "Number order",
    picture: "17 → ❓",
    prompt: "Which number comes just after 17?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "5-6-269",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 17",
    prompt: "Which number comes just before 17?",
    choices: ["16", "17", "15"],
    correct: "16",
  },
  {
    id: "5-6-270",
    ageGroup: "5-6",
    type: "Number order",
    picture: "18 → ❓",
    prompt: "Which number comes just after 18?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "5-6-271",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 18",
    prompt: "Which number comes just before 18?",
    choices: ["17", "18", "16"],
    correct: "17",
  },
  {
    id: "5-6-272",
    ageGroup: "5-6",
    type: "Number order",
    picture: "19 → ❓",
    prompt: "Which number comes just after 19?",
    choices: ["20", "21", "19"],
    correct: "20",
  },
  {
    id: "5-6-273",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 19",
    prompt: "Which number comes just before 19?",
    choices: ["18", "19", "17"],
    correct: "18",
  },
  {
    id: "5-6-274",
    ageGroup: "5-6",
    type: "Number order",
    picture: "20 → ❓",
    prompt: "Which number comes just after 20?",
    choices: ["21", "22", "20"],
    correct: "21",
  },
  {
    id: "5-6-275",
    ageGroup: "5-6",
    type: "Number order",
    picture: "❓ ← 20",
    prompt: "Which number comes just before 20?",
    choices: ["19", "20", "18"],
    correct: "19",
  },
  {
    id: "5-6-276",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐶",
    prompt: "What is a baby dog called?",
    choices: ["Puppy", "Kitten", "Calf"],
    correct: "Puppy",
  },
  {
    id: "5-6-277",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐱",
    prompt: "What is a baby cat called?",
    choices: ["Kitten", "Puppy", "Chick"],
    correct: "Kitten",
  },
  {
    id: "5-6-278",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐮",
    prompt: "What is a baby cow called?",
    choices: ["Calf", "Cub", "Duckling"],
    correct: "Calf",
  },
  {
    id: "5-6-279",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐔",
    prompt: "What is a baby chicken called?",
    choices: ["Chick", "Lamb", "Kitten"],
    correct: "Chick",
  },
  {
    id: "5-6-280",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🦆",
    prompt: "What is a baby duck called?",
    choices: ["Duckling", "Puppy", "Calf"],
    correct: "Duckling",
  },
  {
    id: "5-6-281",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐑",
    prompt: "What is a baby sheep called?",
    choices: ["Lamb", "Chick", "Cub"],
    correct: "Lamb",
  },
  {
    id: "5-6-282",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🐴",
    prompt: "What is a baby horse called?",
    choices: ["Foal", "Kitten", "Lamb"],
    correct: "Foal",
  },
  {
    id: "5-6-283",
    ageGroup: "5-6",
    type: "Animal families",
    picture: "🦁",
    prompt: "What is a baby lion called?",
    choices: ["Cub", "Calf", "Chick"],
    correct: "Cub",
  },
  {
    id: "5-6-284",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐘",
    prompt: "Which animal has a long trunk?",
    choices: ["Elephant", "Rabbit", "Sheep"],
    correct: "Elephant",
  },
  {
    id: "5-6-285",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🦒",
    prompt: "Which animal has a very long neck?",
    choices: ["Giraffe", "Pig", "Cat"],
    correct: "Giraffe",
  },
  {
    id: "5-6-286",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐢",
    prompt: "Which animal carries a hard shell on its back?",
    choices: ["Turtle", "Horse", "Dog"],
    correct: "Turtle",
  },
  {
    id: "5-6-287",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐦",
    prompt: "What covers a bird's body?",
    choices: ["Feathers", "Fur", "Leaves"],
    correct: "Feathers",
  },
  {
    id: "5-6-288",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐟",
    prompt: "What helps a fish swim?",
    choices: ["Fins", "Paws", "Horns"],
    correct: "Fins",
  },
  {
    id: "5-6-289",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🦓",
    prompt: "Which animal has black and white stripes?",
    choices: ["Zebra", "Lion", "Pig"],
    correct: "Zebra",
  },
  {
    id: "5-6-290",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐰",
    prompt: "Which animal has long ears and hops?",
    choices: ["Rabbit", "Cow", "Fish"],
    correct: "Rabbit",
  },
  {
    id: "5-6-291",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐌",
    prompt: "Which animal moves on a broad foot and carries a shell?",
    choices: ["Snail", "Duck", "Bee"],
    correct: "Snail",
  },
  {
    id: "5-6-292",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐔",
    prompt: "Which farm animal clucks?",
    choices: ["Chicken", "Sheep", "Horse"],
    correct: "Chicken",
  },
  {
    id: "5-6-293",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐮",
    prompt: "Which farm animal moos?",
    choices: ["Cow", "Duck", "Pig"],
    correct: "Cow",
  },
  {
    id: "5-6-294",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐑",
    prompt: "Which farm animal grows wool?",
    choices: ["Sheep", "Chicken", "Fish"],
    correct: "Sheep",
  },
  {
    id: "5-6-295",
    ageGroup: "5-6",
    type: "Animal features",
    picture: "🐝",
    prompt: "Which animal makes honey?",
    choices: ["Honeybee", "Cat", "Turtle"],
    correct: "Honeybee",
  },
  {
    id: "5-6-296",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🌱",
    prompt: "Which part of a plant grows down into the soil?",
    choices: ["Roots", "Flowers", "Leaves"],
    correct: "Roots",
  },
  {
    id: "5-6-297",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🌳",
    prompt: "What grows on the branches of many trees?",
    choices: ["Leaves", "Shoes", "Spoons"],
    correct: "Leaves",
  },
  {
    id: "5-6-298",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🌻",
    prompt: "What can grow into a new plant?",
    choices: ["Seed", "Coin", "Button"],
    correct: "Seed",
  },
  {
    id: "5-6-299",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "☀️",
    prompt: "What gives plants light during the day?",
    choices: ["Sun", "Soil", "Rain"],
    correct: "Sun",
  },
  {
    id: "5-6-300",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🍎",
    prompt: "Which food grows on a tree?",
    choices: ["Apple", "Bread", "Cheese"],
    correct: "Apple",
  },
  {
    id: "5-6-301",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🥕",
    prompt: "Which vegetable has a part we eat that grows underground?",
    choices: ["Carrot", "Lettuce", "Peas"],
    correct: "Carrot",
  },
  {
    id: "5-6-302",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🍂",
    prompt: "In many places, when do leaves turn colors and fall?",
    choices: ["Autumn", "Spring", "Summer"],
    correct: "Autumn",
  },
  {
    id: "5-6-303",
    ageGroup: "5-6",
    type: "Plants and nature",
    picture: "🌷",
    prompt: "In many places, which season brings new flowers after winter?",
    choices: ["Spring", "Autumn", "Winter"],
    correct: "Spring",
  },
  {
    id: "5-6-304",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🧊",
    prompt: "What happens to ice when it gets warm?",
    choices: ["It melts", "It grows fur", "It becomes wood"],
    correct: "It melts",
  },
  {
    id: "5-6-305",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "💧",
    prompt: "What can water become when it freezes?",
    choices: ["Ice", "Sand", "Paper"],
    correct: "Ice",
  },
  {
    id: "5-6-306",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "☀️",
    prompt: "Which is a source of light?",
    choices: ["Sun", "Rock", "Shoe"],
    correct: "Sun",
  },
  {
    id: "5-6-307",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🌧️",
    prompt: "What falls from clouds when it rains?",
    choices: ["Water drops", "Pebbles", "Leaves"],
    correct: "Water drops",
  },
  {
    id: "5-6-308",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "👃",
    prompt: "What do you use to smell a flower?",
    choices: ["Nose", "Elbow", "Knee"],
    correct: "Nose",
  },
  {
    id: "5-6-309",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "👀",
    prompt: "What do you use to see colors?",
    choices: ["Eyes", "Ears", "Toes"],
    correct: "Eyes",
  },
  {
    id: "5-6-310",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "👅",
    prompt: "What helps you taste food?",
    choices: ["Tongue", "Hair", "Fingers"],
    correct: "Tongue",
  },
  {
    id: "5-6-311",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🖐️",
    prompt: "Which sense tells you a blanket feels soft?",
    choices: ["Touch", "Hearing", "Sight"],
    correct: "Touch",
  },
  {
    id: "5-6-312",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "⚽",
    prompt: "What makes a still ball start rolling?",
    choices: ["A push", "A song", "A color"],
    correct: "A push",
  },
  {
    id: "5-6-313",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🌙",
    prompt: "What do we often see in the night sky?",
    choices: ["Moon", "A rainbow underground", "A tree root"],
    correct: "Moon",
  },
  {
    id: "5-6-314",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🧲",
    prompt: "Which object can pick up some metal paper clips?",
    choices: ["Magnet", "Feather", "Sponge"],
    correct: "Magnet",
  },
  {
    id: "5-6-315",
    ageGroup: "5-6",
    type: "Simple science",
    picture: "🪨",
    prompt: "Which object is hard?",
    choices: ["Rock", "Pillow", "Cotton ball"],
    correct: "Rock",
  },
];
